### ISSUE TITLE
Change WP admin color scheme on local development URL

### ISSUE THREAD

**Issue by nickdavis** [KnowTheCode/UpDevTools#4]
There’s some code I regularly use that (force) changes the admin colour when I’m working on a local URL which saves me a lot of mistakes, which I think would make a good addition.

**Comment by nickdavis** [comment]
See (tested) example code here:

https://github.com/nickdavis/UpDevTools/commit/83d93d5ff2cd0227572ba9a8ae720ff337e71f88

**Comment by hellofromtonya** [comment]
Added the theme color + admin bar notification and styling to alert that this plugin is active. Thank you, Nick!
