### ISSUE TITLE
assets/vendor/autoload.php missing

### ISSUE THREAD

**Issue by JeffCleverley** [KnowTheCode/UpDevTools#9]
Hey Tonya.

I am getting the following error when trying to activate the updated plugin

`( ! ) Warning: require_once(/app/public/wp-content/plugins/UpDevTools-master/assets/vendor/autoload.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/UpDevTools-master/bootstrap.php on line 54`

Thanks

Jeff

**Comment by JeffCleverley** [comment]
I copied the old vendor folder over from a backup to solve it at my end :)

**Comment by hellofromtonya** [comment]
When you install or upgrade, you need to run `composer install` to bring in the dependencies.  These packages are not committed with this repository.

**Comment by pkpatricia** [comment]
dhcp25:UpDevTools patriciaparker$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

**Comment by pkpatricia** [comment]
this file is located someplace else:

[9:02] 
dhcp25:config patriciaparker$ pwd
/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/config
dhcp25:config patriciaparker$ ls
admin-bar.php
dhcp25:config patriciaparker$

[9:03] 
this is the error i get:

[9:03] 
Whoops\Exception\ErrorException thrown with message “include(/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/assets/css/admin-bar.php): failed to open stream: No such file or directory”
